name: Generate snake animation

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk@3.2.0
          with:
            github_user_name: ${{ github.repository_owner }}
            gif_out_path: dist/snake.gif
            svg_out_path: dist/snake.svg

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
